
all:

init-db:
	docker run --name heset-db --rm -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=pass -p 1434:1434 -it postgres:15.2


docker exec -it [container-id] bash


docker run –name pgsql-dev -e POSTGRES_PASSWORD=Welcome4$ -p 5432:5432 Postgres


docker run -p 4234:4234 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=heset-db -v pgdata:/var/lib/postgresql/data postgres